---
abstract: 'Catalyst based application'
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires:
  Catalyst::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TinyBlog
requires:
  App::mkfeyorm: 0
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80
  Const::Fast: 0
  Fey::DBIManager::Source: 0
  Fey::Loader: 0
  Fey::ORM::Schema: 0
  Fey::ORM::Table: 0
  File::Basename: 0
  File::Path: 0
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  Moose: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  Storable: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources: {}
version: 0.0.1
